### PR TITLE
Add Compiled .EXE

### PR DESCRIPTION
**Pull request by rayliverified**
*Add EyeX files that have been compiled successfully and able to run without errors.

### CODE REVIEW

**Comment by rayliverified** [comment]
Update on this PR?

**Comment by rayliverified** [comment]
Any updates on this PR?

**Comment by ghost** [comment]
> Any updates on this PR?

Not really, I also waited long for updates.
BTW I started a new project. Don't know if someone else is interested in it.
It's a GUI tool, I 'copied' @mikethrussell 's code, and currently working on it.

**Comment by rayliverified** [comment]
I'll just leave the PR open that way anyone that wants to test out the compiled EXE can.

**Comment by rayliverified** [comment]
Thanks @mikethrussell for creating this project and merging this PR!

**Pull request merged**
